### PR TITLE
update landing page to explain what Gym Tracker does

### PR DESCRIPTION
**Pull request by alienware96**
## Execute Code Quality Steps

- [X ] Does this PR include refactors? Detail them below
- [X ] Does this PR include dependency updates? 
- [X ] If the PR includes prisma schema changes, did you create a migration?
- [- ] Run `npm run format` and `npm run lint` on your code

 ## Describe Changes

Updated index and authDisplay pages to reflect new landing page

### CODE REVIEW

**Comment by alienware96** [comment]
this is related to issue #67

**Comment by jessedelira** [comment]
@alienware96 I have made multiple comments on the PR, the link that you added seems to not look like what the PR has. Could you make changes to make the layout support mobile & add more style to it please :)

I can also help in anyway that you need (either writing a description or an opinion on things)

**Comment by alienware96** [comment]
@jessedelira Can you provide me a banner image and descriptions to use.

**Comment by jessedelira** [comment]
I'm going to close this PR for now since it doesn't really align with what we are looking for. When you submit another PR, first create a Figma mock of what things might look like. I would suggest to find an more directed issue to solve, sorry.

**Pull request closed without merging**
