### PR TITLE
Corrected Language Icon

### PR DESCRIPTION
**Pull request by OscarPrimitivo**
## Execute Code Quality Steps

- [ ] Does this PR include refactors? Detail them below
- [ ] Does this PR include dependency updates? 
- [x] Run `npm run format` and `npm run lint` on your code

 ## Describe Changes

Replaced the old language icon with the correct language icon.

### CODE REVIEW

**Comment by jessedelira** [comment]
@OscarPrimitivo did you run "npm run format"? Could you fill out the PR template. Otherwise LTGM and I can merge it 🚀

**Comment by OscarPrimitivo** [comment]
> @OscarPrimitivo did you run "npm run format"? Could you fill out the PR template. Otherwise LTGM and I can merge it 🚀

Yes, I did run it and I filled out the PR template! 💯

**Comment by jessedelira** [comment]
@OscarPrimitivo I left a small comment on the file that I over look 🙈

**Review by jessedelira — APPROVED** [review]
LGTM

**Pull request merged**
